import type { Agent } from "@cloudagi/shared";

export const MOCK_AGENTS: Agent[] = [
  {
    id: "agent_mistral7b",
    provider: "providerWallet1111111111111111111111111111111",
    displayName: "mistral-7b-q4",
    description: "Fast summarization and classification using quantized Mistral 7B.",
    skills: ["summarize.text.v1", "sentiment.classify.v1"],
    pricing: {
      kind: "per_token",
      perMTokensIn: 2,
      perMTokensOut: 4,
    },
    model: {
      kind: "local",
      family: "mistral-7b-instruct",
      quantization: "q4_k_m",
      contextWindow: 32768,
      maxOutputTokens: 4096,
    },
    endpoint: "https://provider1.example.com/api/agent",
    policies: {
      maxPromptTokens: 8192,
      maxOutputTokens: 2048,
      allowedTools: [],
      allowedSkills: ["summarize.text.v1", "sentiment.classify.v1"],
      refuseIfFlags: ["injection", "pii"],
    },
    status: "active",
    stake: 1000000,
    reputation: 97,
    uptimePct: 99.9,
    avgLatencyMs: 340,
    lastHeartbeatAt: new Date().toISOString(),
    createdAt: "2024-01-15T00:00:00Z",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "agent_llama3",
    provider: "providerWallet2222222222222222222222222222222",
    displayName: "llama-3-8b-instruct",
    description: "General purpose instruction following and code generation.",
    skills: ["code.generate.v1", "summarize.text.v1", "qa.answer.v1"],
    pricing: {
      kind: "per_token",
      perMTokensIn: 3,
      perMTokensOut: 6,
    },
    model: {
      kind: "hosted",
      family: "llama-3-8b-instruct",
      contextWindow: 8192,
      maxOutputTokens: 2048,
    },
    endpoint: "https://provider2.example.com/api/agent",
    policies: {
      maxPromptTokens: 4096,
      maxOutputTokens: 2048,
      allowedTools: [],
      allowedSkills: ["code.generate.v1", "summarize.text.v1", "qa.answer.v1"],
      refuseIfFlags: ["injection"],
    },
    status: "active",
    stake: 500000,
    reputation: 94,
    uptimePct: 99.2,
    avgLatencyMs: 520,
    lastHeartbeatAt: new Date().toISOString(),
    createdAt: "2024-02-01T00:00:00Z",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "agent_qwen25",
    provider: "providerWallet3333333333333333333333333333333",
    displayName: "qwen2.5-7b",
    description: "Multilingual model optimized for low-latency edge deployments.",
    skills: ["translate.text.v1", "summarize.text.v1"],
    pricing: {
      kind: "per_token",
      perMTokensIn: 1,
      perMTokensOut: 2,
    },
    model: {
      kind: "local",
      family: "qwen2.5-7b",
      quantization: "q5_k_m",
      contextWindow: 16384,
      maxOutputTokens: 2048,
    },
    endpoint: "https://provider3.example.com/api/agent",
    policies: {
      maxPromptTokens: 8192,
      maxOutputTokens: 2048,
      allowedTools: [],
      allowedSkills: ["translate.text.v1", "summarize.text.v1"],
      refuseIfFlags: ["injection", "pii", "unsafe_code"],
    },
    status: "active",
    stake: 750000,
    reputation: 96,
    uptimePct: 99.8,
    avgLatencyMs: 180,
    lastHeartbeatAt: new Date().toISOString(),
    createdAt: "2024-03-01T00:00:00Z",
    updatedAt: new Date().toISOString(),
  },
];
